name: Guppy Build

on:
  pull_request:
    types: ['opened', 'synchronize']
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Guppy
        run: ./gradlew clean lint assembleDebug jacocoTestReportCoverage -PdisablePreDex

      - name: Calculate Test Coverage
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: guppy/build/reports/jacoco/jacocoTestReportCoverage/jacoco.xml
